version: "3"

env:
  BORDER: double
  BORDER_FOREGROUND: "212"
  PADDING: "1 1"
  MARGIN: "1 1"
  NAMESPACE: 04--service

tasks:
  01-create-namespace:
    desc: "Create a namespace for these examples and set as default"
    cmds:
      - kubectl apply -f Namespace.yaml
      - kubens ${NAMESPACE}

  02-apply-deployment:
    desc: "Apply the Deployment configuration"
    cmds:
      - kubectl apply -f Deployment.yaml

  03-apply-clusterip-service:
    desc: "Apply the ClusterIP Service"
    cmds:
      - kubectl apply -f Service.nginx-clusterip.yaml

  04-apply-nodeport-service:
    desc: "Apply the  NodePort Service"
    cmds:
      - kubectl apply -f Service.nginx-nodeport.yaml
      - cmd: gum style "💡 Add a firewall rule to allow inbound traffic for nodeport port!"
        silent: true

  05-apply-loadbalancer-service:
    desc: "Apply the  LoadBalancer Service"
    cmds:
      - kubectl apply -f Service.nginx-loadbalancer.yaml

  06-delete-namespace:
    desc: "Delete the namespace to clean up"
    cmds:
      - cmd: gum style "🚨 Deleting the namespace recursively deletes the resources inside of it! 🚨 "
        silent: true
      - kubectl delete -f Namespace.yaml

  07-tester-pod:
    desc: "Create interactive pod in namespace to test above setup"
    cmds:
      - cmd: gum style "💡 Type exit to quit."
      - kubectl run curl-pod -it --rm --image=curlimages/curl --command -- sh

  08-tester-cross-ns:
    desc: "Create interactive pod in namespace to test above setup"
    cmds:
      - cmd: gum style "💡 curl across ns using nginx-clusterip.04--service.svc.cluster.local"
      - kubectl run curl-pod -it --rm -n default --image=curlimages/curl --command -- sh

  09-run-cloud-provider-kind:
    desc: "KinD Load Balance same as lesson 3 sigs.k8s.io/cloud-provider-kind@latest"
    cmds:
      - kubectl label node kind-control-plane node.kubernetes.io/exclude-from-external-load-balancers-node/kind-control-plane-
      - cloud-provider-kind