# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
    - containerPort: 30080
      hostPort: 30080
      listenAddress: "0.0.0.0"
      protocol: tcp
  - role: worker
    extraMounts:
      - hostPath: /media/renderws/carltonData/cj2024/code/devbox/devops-directive-kubernetes-course/03-installation-and-setup/kind-bind-mount-1
        containerPath: /some/path/in/container
  - role: worker
    extraMounts:
      - hostPath: /media/renderws/carltonData/cj2024/code/devbox/devops-directive-kubernetes-course/03-installation-and-setup/kind-bind-mount-2
        containerPath: /some/path/in/container
