version: "3"

env:
  BORDER: double
  BORDER_FOREGROUND: "212"
  PADDING: "1 1"
  MARGIN: "1 1"
  NAMESPACE: 99--cj-kind-loadbalancer

tasks:
  00-delete-cluster:
    desc: Delete an existing a kind Kubernetes cluster
    cmds:
      - kind delete cluster
  
  01-create-cluster:
    desc: Create a Kubernetes cluster using kind
    cmds:
      - kind create cluster --config kind-config.yaml

  02-create-namespace:
    desc: "Create a namespace for these examples and set as default"
    cmds:
      - kubectl apply -f Namespace.yaml
      - kubens ${NAMESPACE}

  03-run-cloud-provider-kind:
    desc: "KinD Load Balance same as lesson 3 sigs.k8s.io/cloud-provider-kind@latest"
    cmds:
      - kubectl label node kind-control-plane node.kubernetes.io/exclude-from-external-load-balancers-node/kind-control-plane-
      - cloud-provider-kind

  04-apply-ds:
    desc: "Apply the Deployment and Service"
    cmds:
      - kubectl apply -f loadbalancer_etp_local.yaml

  05-delete-namespace:
    desc: "Delete the namespace to clean up"
    cmds:
      - cmd: gum style "🚨 Deleting the namespace recursively deletes the resources inside of it! 🚨 "
        silent: true
      - kubectl delete -f Namespace.yaml

  06-tester-pod:
    desc: "Create interactive pod in namespace to test above setup"
    cmds:
      - cmd: gum style "💡 Type exit to quit."
      - kubectl run curl-pod -it --rm --image=curlimages/curl --command -- sh

  100-create-nginx:
    desc: "Create nginx yaml"
    cmds:
      - rm -f nginx.yml
      - kubectl run nginx --image=nginx --port=80 --dry-run=client -o yaml > nginx.yml

  101-apply-nginx:
    desc: "Apply nginx"
    cmds:
      - kubectl apply -f nginx.yml

  102-create-nginx-nodeport:
    desc: "Create nginx nodeport"
    cmds:
      - rm -f nginx-nodeport.yml
      - kubectl expose pod nginx --name=nginx-nodeport --type=NodePort --port=80 --target-port=80 --dry-run=client -o yaml > nginx-nodeport.yml
  
  103-apply-nodeport:
    desc: "Apply nodeport"
    cmds:
      - kubectl apply -f nginx-nodeport.yml
  
  104-test-nodeport:
    desc: "Test nodeport"
    cmds:
      - curl http://localhost:30080
  
  105-delete-nginx:
    desc: "Delete nginx"
    cmds:
      - kubectl delete -f nginx.yml
